---
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: 
sections:
- type: jekyll-pages
  label: Pages
  create: all
- type: jekyll-posts
  label: Posts
  create: all
- type: heading
  label: Library
- type: directory
  path: _lib-tags-first
  label: Tags first
  create: documents
  match: "**/*"
  templates:
  - tag-tag
- type: directory
  path: _lib-var-options
  label: CSS variables
  create: documents
  match: "**/*"
  templates:
  - tag-tag
- type: directory
  path: _lib-fonts
  label: Fonts
  create: documents
  match: "**/*"
  templates:
  - tags-font
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
  publish_command: bundle exec jekyll build -d _site
  preview_env:
  - JEKYLL_ENV=staging
  publish_env:
  - JEKYLL_ENV=production
  preview_output_directory: _site
  output_directory: _site
