---
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: 
sections:
- type: jekyll-pages
  label: Pages
  create: all
- type: jekyll-posts
  label: Posts
  create: all
- type: heading
  label: Library
- type: directory
  path: _lib-tags-first
  label: Tags first
  create: all
  match: "**/*"
- type: directory
  path: _lib-var-options
  label: CSS variables
  create: all
  match: "**/*"
  templates:
  - tag-tag
- type: directory
  path: _lib-fonts
  label: Fonts
  create: all
  match: "**/*"
  templates:
  - tags-font
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
